steps:
  # Pull the previous latest image to use as cache
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker pull gcr.io/$PROJECT_ID/drive-receiver:latest || exit 0']

  # Build the container image with caching
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/drive-receiver:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/drive-receiver:latest'
      - '--cache-from'
      - 'gcr.io/$PROJECT_ID/drive-receiver:latest'
      - 'services/drive-receiver/'
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/drive-receiver', '--all-tags']
  
  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'drive-receiver'
      - '--image'
      - 'gcr.io/$PROJECT_ID/drive-receiver:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--project'
      - '$PROJECT_ID'
      
images:
  - 'gcr.io/$PROJECT_ID/drive-receiver:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/drive-receiver:latest'
